# German layout by Mark Müller
# Version 2019111700
---
bounds: { x: 0, y: 1, width: 360, height: 208 }

outlines:
    default:
        bounds: { x: 0, y: 0, width: 35.33, height: 52 }
    altline:
        bounds: { x: 0, y: 0, width: 52.67, height: 52 }
    wide:
        bounds: { x: 0, y: 0, width: 62, height: 52 }
    spaceline:
        bounds: { x: 0, y: 0, width: 99.67, height: 52 }
    special:
        bounds: { x: 0, y: 0, width: 35.33, height: 52 }

views:
    base:
        - "q w e r t z u i o p"
        - "a s d f g h j k l"
        - "Shift_L   y x c v b n m  BackSpace"
        - "show_numbers show_eschars preferences         space        , . Return"
    upper:
        - "Q W E R T Z U I O P"
        - "A S D F G H J K L"
        - "Shift_L   Y X C V B N M  BackSpace"
        - "show_numbers show_eschars preferences         space        ! ? Return"
    numbers:
        - "1 2 3 4 5 6 7 8 9 0"
        - "@ # € % & - _ + ( )"
        - "show_symbols   , \" ' : = < >  BackSpace"
        - "show_letters show_eschars preferences         space        , . Return"
    symbols:
        - "~ ` ´ | · √ µ ÷ × ¶"
        - "© ® £ $ ¥ ^ ° * { }"
        - "show_numbers   \\ / § π τ [ ]  BackSpace"
        - "show_letters show_eschars preferences         space        , . Return"
    eschars:
        - "ä è é ö ü Ä È É Ö Ü"
        - "à â ê î ô À Â È Î Ô"
        - "show_numbers  « » ç Ç æ œ ß  BackSpace"
        - "show_letters show_eschars preferences         space        „ “ Return"

buttons:
    Shift_L:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "altline"
        icon: "key-shift"
    BackSpace:
        outline: "altline"
        icon: "edit-clear-symbolic"
        keysym: "BackSpace"
    preferences:
        action: "show_prefs"
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "altline"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "altline"
        label: "abc"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "altline"
        label: "*/="
    show_eschars:
        action:
            locking:
                lock_view: "eschars"
                unlock_view: "base"
        outline: "altline"
        label: "äÄ"
    space:
        outline: "spaceline"
        label: " "
        keysym: "space"
    Return:
        outline: "altline"
        icon: "key-enter"
        keysym: "Return"
