# Greek layout created by Antonis Tsolomitis
# University of the Aegean, Department of Mathematics, atsol@aegean.gr
# Sep 2019
---
bounds: { x: 0, y: 0.33, width: 360, height: 210 }

outlines:
    default:
        bounds: { x: 0, y: 0, width: 32, height: 52 }
    altline:
        bounds: { x: 0, y: 0, width: 48.39024, height: 52 }
    wide:
        bounds: { x: 0, y: 0, width: 62, height: 52 }
    outline7:
        bounds: { x: 0, y: 0, width: 88.97561, height: 52 }
    spaceline:
        bounds: { x: 0, y: 0, width: 150.5853, height: 52 }

views:
    base:
        - "; ς ε ρ τ υ θ ι ο π !"
        - "α σ δ φ γ η ξ κ λ show_accented"
        - "Shift_L ζ χ ψ ω β ν μ , BackSpace"
        - "show_numbers preferences space period Return"
    upper:
        - ": EuroSign Ε Ρ Τ Υ Θ Ι Ο Π"
        - "Α Σ Δ Φ Γ Η Ξ Κ Λ show_accented"
        - "Shift_L Ζ Χ Ψ Ω Β Ν Μ · BackSpace"
        - "show_numbers preferences space « » Return"
    accented:
        - "ά έ ή ί ό ύ ώ ϊ ϋ ΐ"
        - "ΰ Ά Έ Ή Ί Ό Ύ Ώ Ϊ show_base"
        - "Ϋ Ϗ ϐ ϑ ϕ ϖ ϗ – — BackSpace"
        - "show_numbers preferences space quoteleft quoteright Return"
    numbers:
        - "1 2 3 4 5 6 7 8 9 0"
        - "at numbersign dollar percent ampersand minus underscore plus parenleft parenright"
        - "show_symbols comma quotedbl quoteright colon semicolon exclam question BackSpace"
        - "show_letters preferences space period Return"
    symbols:
        - "asciitilde quoteleft bar U00B7 squareroot Greek_pi Greek_tau division multiply paragraph"
        - "copyright U00AE U00A3 EuroSign U00A5 asciicircum degree asterisk braceleft braceright"
        - "show_numbers backslash slash less greater equal bracketleft bracketright  BackSpace"
        - "show_letters preferences space period Return"
buttons:
    Shift_L:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "altline"
        icon: "key-shift"
    BackSpace:
        outline: "altline"
        icon: "edit-clear-symbolic"
    preferences:
        action: "show_prefs"
        outline: "altline"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "altline"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "altline"
        label: "ΑΒΓ"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "altline"
        label: "*/="
    show_accented:
        action:
            locking:
                lock_view: "accented"
                unlock_view: "base"
        outline: "altline"
        label: "άΐ"
    show_base:
        action:
            set_view: "base"
        outline: "altline"
        label: "αι"
    period:
        outline: "altline"
        label: "."
    space:
        outline: spaceline
        label: " "
    Return:
        outline: "wide"
        icon: "key-enter"
    aring:
        label: "å"
    Aring:
        label: "Å"
    oslash:
        label: "ø"
    Oslash:
        label: "Ø"
    ae:
        label: "æ"
    AE:
        label: "Æ"
    asterisk:
        label: "*"
    asciitilde:
        label: "~"
    quoteleft:
        label: "`"
    bar:
        label: "|"
    U00B7:
        label: "·"
    squareroot:
        label: "√"
    Greek_pi:
        label: "π"
    division:
        label: "÷"
    multiply:
        label: "×"
    paragraph:
        label: "¶"
    Greek_tau:
        label: "τ"
    copyright:
        label: "©"
    numbersign:
        label: "#"
    U00AE:
        label: "®"
    at:
        label: "@"
    dollar:
        label: "$"
    U00A3:
        label: "£"
    percent:
        label: "%"
    EuroSign:
        label: "€"
    ampersand:
        label: "&"
    U00A5:
        label: "¥"
    minus:
        label: "-"
    asciicircum:
        label: "^"
    underscore:
        label: "_"
    degree:
        label: "°"
    plus:
        label: "+"
    equal:
        label: "="
    parenleft:
        label: "("
    parenright:
        label: ")"
    braceleft:
        label: "{"
    braceright:
        label: "}"
    comma:
        label: ","
    backslash:
        label: "\\"
    slash:
        label: "/"
    quotedbl:
        label: "\""
    quoteright:
        label: "'"
    less:
        label: "<"
    greater:
        label: ">"
    colon:
        label: ":"
    semicolon:
        label: ";"
    exclam:
        label: "!"
    question:
        label: "?"
    bracketleft:
        label: "["
    bracketright:
        label: "]"

